name: CI
on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo test --all
    - name: "Test with Windows 10+ feature"
      run: cargo test --all --features win10plus
      if: matrix.os == 'windows-latest'
    - run: cargo run --example uptime

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: fmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --all --all-targets --all-features -- -D warnings

    - name: Docs
      run: cargo doc
